#add stages here 
stages:
  Data_Ingestion:
    cmd: python src/templates/stage_01_dataingestion_prep.py
    deps:
    - src/templates/stage_01_dataingestion_prep.py
    - src/components/Data_Ingestion_Component.py
    outs:
    - artifacts/train_ds
    - artifacts/test_ds
    - artifacts/encoder.pkl
